// Core

export const GET_HYDRAULIC_PUMP = 'GET_HYDRAULIC_PUMP';
export const SET_VIEW_ELEMENT = 'SET_VIEW_ELEMENT';
export const SET_HOVERED_HYDRAULIC_PUMP = 'SET_HOVERED_HYDRAULIC_PUMP';
export const SET_HOVERED_ROVER = 'SET_HOVERED_ROVER';
export const SET_HOVERED_HYDRAULIC_PUMP_ALERT = 'SET_HOVERED_HYDRAULIC_PUMP_ALERT';
export const SET_ROVER_CONNECTIONS = 'SET_ROVER_CONNECTIONS';
export const SET_ROVER_POSITION = 'SET_ROVER_POSITION';
export const SET_SITE_DIAGRAM_POSITION = 'SET_SITE_DIAGRAM_POSITION';
export const SET_MANIFOLD_POSITION = 'SET_MANIFOLD_POSITION';